name: CI/CD Deploy to Windows Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Fazer checkout do código do repositório
      - name: Checkout code
        uses: actions/checkout@v2

      # Publicar a API
      - name: Publish .NET API
        run: |
          cd ApiMinhasFinancas # ou o caminho correto se estiver em uma pasta diferente
          dotnet publish ApiMinhasFinancas.sln -c Release -o ./output

      # Fazer deploy no servidor Windows via SSH
      - name: Deploy to Windows Server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.WINDOWS_SERVER_HOST }}
          username: ${{ secrets.WINDOWS_SERVER_USER }}
          key: ${{ secrets.WINDOWS_SERVER_SSH_KEY }}
          port: 22
          script: |
            cd C:\Users\Administrator\Desktop\Api Minhas Financas
            git pull origin main
            dotnet restore ApiMinhasFinancas.sln
            dotnet build ApiMinhasFinancas.sln --configuration Release
            dotnet run --no-build
